gitlab:
  image: 'gitlab/gitlab-ce:latest'
  container_name: gitlab
  restart: always
  hostname: 'gitlab.ridi.io'
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - './volumes/config:/etc/gitlab'
    - './volumes/logs:/var/log/gitlab'
    - './volumes/app:/var/opt/gitlab'
