gitlab:
  image: gitlab/gitlab-ce:${IMAGE_TAG}
  container_name: gitlab
  restart: always
  hostname: 'gitlab.ridi.io'
  ports:
    - '443:443'
    - '22:22'
  volumes:
    - './volumes/config:/etc/gitlab'
    - './volumes/logs:/var/log/gitlab'
    - './volumes/app:/var/opt/gitlab'
    - './volumes/secret/:/secret'
